variable "project" {}
variable "env" {}
variable "image_names" {}
variable "tags" {}
variable "region" {}
variable "s3_model_bucket" {}
variable "container_ports" {}
variable "image_urls" {}
variable "security_groups_ecs" {}
variable "subnets_public" {}
variable "public_ip" {}
variable "lb_tg_arns" {}
variable "cpu" {}
variable "memory" {}
variable "shutdown" {}
variable "turnon" {}