variable "project" {}
variable "company" {}
variable "env" {}
variable "vpc_id" {}
variable "tags" {}
variable "security_groups_lb" {}
variable "subnets" {}
variable "path_route" {}
variable "timeout" {}
variable "interval" {}
